version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py  # Adjust this if your conf.py is elsewhere

python:
  install:
    - requirements: requirements.txt  # Ensure your requirements are listed here

caching:
  paths:
    - docs/build/   # or any directory where your build is located
